# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://yh-eric-chan.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Yihong(Eric) Chen Personal Website"
description: This is website for Yihong Chen

# color theme for links
theme-color: pink # indigo|yellow|pink|green|stone|

# homepage information
author: Yihong Chen
author-bio: Senior Student in MIS & Math & Data Science # change to false to hide
author-image: IMG_6557.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Research
  permalink: research
- text: CV
  permalink: cv
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/yh-eric-chan
linkedin: https://linkedin.com/in/eric-yihong-chen
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
